#!/bin/bash

DEV=${1}
SIZE=${2}

if [ "x${DEV}" == "x" ]; then
	echo "usage: expand dev size"
	exit 0
fi

if [ $(whoami) != "root" ]; then
	echo "You are not super enough ... like me ..."
	exit -1
fi

which resize2fs >/dev/null

if [ $? != 0 ]; then
	echo "resize2fs is missing or stupid ..."
	exit -2
fi

which fdisk >/dev/null

if [ $? != 0 ]; then
	echo "fdisk is missing or stupid ..."
	exit -3
fi

which fsck >/dev/null

if [ $? != 0 ]; then
	echo "fsck is missing or stupid ..."
	exit -4
fi

which grep >/dev/null

if [ $? != 0 ]; then
	echo "grep is missing or stupid ..."
	exit -5
fi

sync

if [ ! -b $DEV ]; then
	echo "${DEV} is not a valid block device ... need a full path to a block device in /dev"
	exit -6
fi

MOUNTS=$(grep -F ${DEV}1 /proc/mounts)

if [ $? == 0 ]; then
	echo "${DEV}1 (boot) looks mounted:"
	echo $MOUNTS
	exit -7
fi

MOUNTS=$(grep -F ${DEV}2 /proc/mounts)

if [ $? == 0 ]; then
	echo "${DEV}2 (root) looks mounted:"
	echo $MOUNTS
	exit -7
fi

MOUNTS=$(grep -F ${DEV}3 /proc/mounts)

if [ $? == 0 ]; then
	echo "${DEV}3 (user) looks mounted:"
	echo $MOUNTS
	exit -7
fi

fdisk ${DEV} >/dev/null <<END
d
3
n
p
3

${SIZE}
w
END

sync

sleep 3

fsck.ext2 -p ${DEV}3

ESTATUS=$?

sync

resize2fs -p ${DEV}3

ESTATUS=$?

sync

exit $ESTATUS
